/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register-device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DeviceRegistrationResponse"];
                        "application/json": components["schemas"]["DeviceRegistrationResponse"];
                        "text/json": components["schemas"]["DeviceRegistrationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coping/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CopingExerciseDto"][];
                        "application/json": components["schemas"]["CopingExerciseDto"][];
                        "text/json": components["schemas"]["CopingExerciseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coping/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CopingSessionDto"][];
                        "application/json": components["schemas"]["CopingSessionDto"][];
                        "text/json": components["schemas"]["CopingSessionDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StartCopingSessionRequest"];
                    "text/json": components["schemas"]["StartCopingSessionRequest"];
                    "application/*+json": components["schemas"]["StartCopingSessionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coping/sessions/{sessionId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CompleteCopingSessionRequest"];
                    "text/json": components["schemas"]["CompleteCopingSessionRequest"];
                    "application/*+json": components["schemas"]["CompleteCopingSessionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/JournalEntries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JournalEntryDto"][];
                        "application/json": components["schemas"]["JournalEntryDto"][];
                        "text/json": components["schemas"]["JournalEntryDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateJournalEntryRequest"];
                    "text/json": components["schemas"]["CreateJournalEntryRequest"];
                    "application/*+json": components["schemas"]["CreateJournalEntryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserPreferencesDto"];
                        "application/json": components["schemas"]["UserPreferencesDto"];
                        "text/json": components["schemas"]["UserPreferencesDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdatePreferencesRequest"];
                    "text/json": components["schemas"]["UpdatePreferencesRequest"];
                    "application/*+json": components["schemas"]["UpdatePreferencesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CompleteCopingSessionRequest: {
            /** Format: date-time */
            completedAtUtc?: string | null;
        };
        CopingExerciseDto: {
            /** Format: int32 */
            id?: number;
            code?: string | null;
            name?: string | null;
            description?: string | null;
        };
        CopingSessionDto: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            exerciseId?: number;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string | null;
        };
        CreateJournalEntryRequest: {
            /** Format: date */
            date?: string;
            text?: string | null;
            /** Format: int32 */
            moodRating?: number | null;
            /** Format: int32 */
            sleepHours?: number | null;
            tags?: string | null;
        };
        DeviceRegistrationResponse: {
            /** Format: uuid */
            userId?: string;
            deviceToken?: string | null;
        };
        JournalEntryDto: {
            /** Format: uuid */
            id?: string;
            /** Format: date */
            date?: string;
            text?: string | null;
            /** Format: int32 */
            moodRating?: number | null;
            /** Format: int32 */
            sleepHours?: number | null;
            tags?: string | null;
        };
        StartCopingSessionRequest: {
            /** Format: int32 */
            exerciseId?: number;
            /** Format: date-time */
            startedAtUtc?: string | null;
        };
        UpdatePreferencesRequest: {
            timeZoneId?: string | null;
            scriptureModeEnabled?: boolean;
        };
        UserPreferencesDto: {
            scriptureModeEnabled?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
